# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcodecs': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kjobwidgets': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kwidgetaddons': '@stable'
    'sdk/libkomparediff2': '@same'
